Repository DanLevyM/challengeOne, pull requests merged in 2023-01, with the labels that each got.

#14 Front/handle router
  vite-vue/films.json
  vite-vue/src/App.vue
  vite-vue/src/components/GoBack.vue
  vite-vue/src/components/HelloWorld.vue
  vite-vue/src/components/TheNavigation.vue
  vite-vue/src/main.ts
  vite-vue/src/router/router.ts
  vite-vue/src/style.css
  vite-vue/src/views/Demo.vue
  vite-vue/src/views/NotFound.vue
  vite-vue/src/views/about/About.vue
  vite-vue/src/views/auth/Login.vue
  vite-vue/src/views/auth/Register.vue
  vite-vue/src/views/home/Home.vue
Labels: frontend

#15 Front add bootstrap + navbar
  vite-vue/index.html
  vite-vue/src/components/TheNavigation.vue
  vite-vue/src/views/NotFound.vue
Labels: frontend

#16 Add/entities
  api/composer.json
  api/config/bundles.php
  api/config/packages/hautelook_alice.yaml
  api/config/packages/nelmio_alice.yaml
  api/migrations/Version20230117154133.php
  api/migrations/Version20230118102414.php
  api/src/DataFixtures/AppFixtures.php
  api/src/DataFixtures/CommentFixture.php
  api/src/DataFixtures/ModerationFixture.php
  api/src/DataFixtures/MovieFixture.php
  api/src/DataFixtures/MovieRoomFixture.php
  api/src/DataFixtures/ProductFixture.php
  api/src/DataFixtures/ReviewFixture.php
  api/src/DataFixtures/SeanceFixture.php
  api/src/DataFixtures/SubscriptionFixture.php
  api/src/DataFixtures/TicketFixture.php
  api/src/DataFixtures/UserFixture.php
  api/src/Entity/Comment.php
  api/src/Entity/Moderation.php
  api/src/Entity/Movie.php
  api/src/Entity/MovieRoom.php
  api/src/Entity/Product.php
  api/src/Entity/Review.php
  api/src/Entity/Seance.php
  api/src/Entity/Subscription.php
  api/src/Entity/Ticket.php
  api/src/Entity/User.php
  api/src/Repository/CommentRepository.php
  api/src/Repository/ModerationRepository.php
  api/src/Repository/MovieRepository.php
  api/src/Repository/MovieRoomRepository.php
  api/src/Repository/ProductRepository.php
  api/src/Repository/ReviewRepository.php
  api/src/Repository/SeanceRepository.php
  api/src/Repository/SubscriptionRepository.php
  api/src/Repository/TicketRepository.php
  api/src/Repository/UserRepository.php
  api/symfony.lock
Labels: backend

#19 Front/auth login register
  vite-vue/package-lock.json
  vite-vue/package.json
  vite-vue/src/components/TheNavigation.vue
  vite-vue/src/datas/movies.json
  vite-vue/src/datas/users.json
  vite-vue/src/main.ts
  vite-vue/src/router/router.ts
  vite-vue/src/stores/MovieStore.js
  vite-vue/src/stores/UserStore.ts
  vite-vue/src/views/auth/Login.vue
  vite-vue/src/views/auth/Register.vue
  vite-vue/src/views/home/Home.vue
  vite-vue/src/views/movie/Movies.vue
  vite-vue/src/views/movie/components/MovieItem.vue
Labels: frontend

#21 CI - basic ci for build and test front and back
  .github/workflows/ga-apiplatform.yml
  .github/workflows/ga-vue.yml
  api/.gitignore
  api/composer.json
  api/composer.lock
  api/config/packages/doctrine.yaml
  api/symfony.lock
  vite-vue/.gitignore
  vite-vue/package-lock.json
  vite-vue/package.json
  vite-vue/src/components/__test__/TheNavigation.test.ts
  vite-vue/src/stores/UserStore.ts
  vite-vue/src/views/auth/Login.vue
Labels: ci-cd
